coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
      application:
        target: auto
        threshold: 0%
        paths: packages/application
      battery:
        target: auto
        threshold: 0%
        paths: packages/battery
      brightness:
        target: auto
        threshold: 0%
        paths: packages/brightness
      font:
        target: auto
        threshold: 0%
        paths: packages/font
      permissions:
        target: auto
        threshold: 0%
        paths: packages/permissions
      screen-orientation:
        target: auto
        threshold: 0%
        paths: packages/screen-orientation
      sensors:
        target: auto
        threshold: 0%
        paths: packages/sensors
      store-review:
        target: auto
        threshold: 0%
        paths: packages/store-review
      web-browser:
        target: auto
        threshold: 0%
        paths: packages/web-browser
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
